name: Vowel Frequency Analyzer
description: Analyzes vowel frequency in data.txt

inputs:
  file:
    description: Path to text file
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.file }}
